# GitHub CLI Configuration
# This file configures GitHub CLI for the VocalInk project

# Default repository
repo: "akku2005/VocalInk"

# Issue templates
issue_templates:
  - name: "Bug Report"
    description: "Create a report to help us improve"
    labels: ["bug"]
  - name: "Feature Request"
    description: "Suggest an idea for this project"
    labels: ["enhancement"]
  - name: "Documentation"
    description: "Suggest improvements to the documentation"
    labels: ["documentation"]

# Pull request templates
pull_request_template: |
  ## Description
  Please include a summary of the change and which issue is fixed.

  ## Type of change
  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] Documentation update

  ## Checklist
  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing unit tests pass locally with my changes
  - [ ] Any dependent changes have been merged and published in downstream modules

# Release configuration
release:
  draft: false
  prerelease: false
  generate_release_notes: true

# Workflow configuration
workflow:
  auto_merge: false
  delete_branch_on_merge: true 