export { default as ProfileTab } from './ProfileTab';
export { default as AccountTab } from './AccountTab';
export { default as PrivacyTab } from './PrivacyTab';
export { default as NotificationsTab } from './NotificationsTab';
export { default as AppearanceTab } from './AppearanceTab';
export { default as AIPreferencesTab } from './AIPreferencesTab';
export { default as GamificationTab } from './GamificationTab';
export { default as SecurityTab } from './SecurityTab';
export { default as SettingsPage } from './SettingsPage';
